{
 "title": "System",
 "tags": [ "linux" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   { "name": "diskdevices", "query": "[a-z]+|nvme[0-9]+n[0-9]+" }
  ]
 },
 "panels": [
  { "title": "System Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Processes Status",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "counter" }
   ],
   "targets": [
    {
     "expr": "node_procs_blocked{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Processes blocked waiting for I/O to complete"
    },
    {
     "expr": "node_procs_running{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Processes in runnable state"
    }
   ]
  },
  {
   "title": "Processes State",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "counter" }
   ],
   "targets": [
    {
     "expr": "node_processes_state{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Processes  Forks",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "forks / sec" }
   ],
   "targets": [
    {
     "expr": "rate(node_forks_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Processes forks second"
    }
   ]
  },
  {
   "title": "Processes Memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "decbytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(process_virtual_memory_bytes{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Processes virtual memory size in bytes"
    },
    {
     "expr": "process_resident_memory_max_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Maximum amount of virtual memory available in bytes"
    },
    {
     "expr": "rate(process_virtual_memory_bytes{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Processes virtual memory size in bytes"
    },
    {
     "expr": "rate(process_virtual_memory_max_bytes{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Maximum amount of virtual memory available in bytes"
    }
   ]
  },
  {
   "title": "PIDs Number and Limit",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "counter" }
   ],
   "targets": [
    {
     "expr": "node_processes_pids{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Number of PIDs"
    },
    {
     "expr": "node_processes_max_processes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "PIDs limit"
    }
   ]
  },
  {
   "title": "Process schedule stats Running / Waiting",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "s", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "rate(node_schedstat_running_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "CPU {{ cpu }} - seconds spent running a process"
    },
    {
     "expr": "rate(node_schedstat_waiting_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "CPU {{ cpu }} - seconds spent by processing waiting for this CPU"
    }
   ]
  },
  {
   "title": "Threads Number and Limit",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "counter" }
   ],
   "targets": [
    {
     "expr": "node_processes_threads{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Allocated threads"
    },
    {
     "expr": "node_processes_max_threads{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Threads limit"
    }
   ]
  },
  {
   "title": "System Timesync",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time Syncronized Drift",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "s", "label": "seconds" }
     ],
     "targets": [
      {
       "expr": "node_timex_estimated_error_seconds{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Estimated error in seconds"
      },
      {
       "expr": "node_timex_offset_seconds{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Time offset in between local system and reference clock"
      },
      {
       "expr": "node_timex_maxerror_seconds{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Maximum error in seconds"
      }
     ]
    },
    {
     "title": "Time PLL Adjust",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "node_timex_loop_time_constant{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Phase-locked loop time adjust"
      }
     ]
    },
    {
     "title": "Time Syncronized Status",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "node_timex_sync_status{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Is clock synchronized to a reliable server (1 = yes, 0 = no)"
      },
      {
       "expr": "node_timex_frequency_adjustment_ratio{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Local clock frequency adjustment"
      }
     ]
    },
    {
     "title": "Time Misc",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "s", "label": "seconds" }
     ],
     "targets": [
      {
       "expr": "node_timex_tick_seconds{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Seconds between clock ticks"
      },
      {
       "expr": "node_timex_tai_offset_seconds{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "International Atomic Time (TAI) offset"
      }
     ]
    }
   ]
  },
  {
   "title": "System Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Context Switches / Interrupts",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "rate(node_context_switches_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Context switches"
      },
      {
       "expr": "rate(node_intr_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Interrupts"
      }
     ]
    },
    {
     "title": "System Load",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "node_load1{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Load 1m"
      },
      {
       "expr": "node_load5{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Load 5m"
      },
      {
       "expr": "node_load15{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Load 15m"
      }
     ]
    },
    {
     "title": "Interrupts Detail",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "rate(node_interrupts_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ type }} - {{ info }}"
      }
     ]
    },
    {
     "title": "Schedule timeslices executed by each cpu",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "rate(node_schedstat_timeslices_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "CPU {{ cpu }}"
      }
     ]
    },
    {
     "title": "Entropy",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "node_entropy_available_bits{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Entropy available to random number generators"
      }
     ]
    },
    {
     "title": "CPU time spent in user and system contexts",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "s", "label": "seconds" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Time spent"
      }
     ]
    },
    {
     "title": "File Descriptors",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "process_max_fds{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Maximum open file descriptors"
      },
      {
       "expr": "process_open_fds{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Open file descriptors"
      }
     ]
    }
   ]
  },
  {
   "title": "Hardware Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hardware temperature monitor",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "celsius", "label": "temperature" }
     ],
     "targets": [
      {
       "expr": "node_hwmon_temp_celsius{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "{{ chip }} {{ sensor }} temp"
      },
      {
       "expr": "node_hwmon_temp_crit_celsius{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "{{ chip }} {{ sensor }} Critical"
      }
     ]
    },
    {
     "title": "Throttle cooling device",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "node_cooling_device_cur_state{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Current {{ name }} in {{ type }}"
      },
      {
       "expr": "node_cooling_device_max_state{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Max {{ name }} in {{ type }}"
      }
     ]
    },
    {
     "title": "Power supply",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "node_power_supply_online{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "{{ power_supply }} online"
      }
     ]
    }
   ]
  },
  {
   "title": "Systemd",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Systemd Sockets",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "rate(node_systemd_socket_accepted_connections_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ name }} Connections"
      }
     ]
    },
    {
     "title": "Systemd Units State",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short", "label": "counter" }
     ],
     "targets": [
      {
       "expr": "node_systemd_units{instance=\"$node\",job=\"$job\",state=\"activating\"}",
       "legendFormat": "Activating"
      },
      {
       "expr": "node_systemd_units{instance=\"$node\",job=\"$job\",state=\"active\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "node_systemd_units{instance=\"$node\",job=\"$job\",state=\"deactivating\"}",
       "legendFormat": "Deactivating"
      },
      {
       "expr": "node_systemd_units{instance=\"$node\",job=\"$job\",state=\"failed\"}",
       "legendFormat": "Failed"
      },
      {
       "expr": "node_systemd_units{instance=\"$node\",job=\"$job\",state=\"inactive\"}",
       "legendFormat": "Inactive"
      }
     ]
    }
   ]
  }
 ]
}