#!/bin/sh
P=$(cd "$(dirname "$0")"; pwd)
cd $P
cd ../Resources/grafana-server && bin/grafana-server 
cd ../Resources/prometheus --web.listen-address=127.0.0.1:9090  && ./prometheus 
cd ../Resources/node_exporter && ./node_exporter
open http://localhost:3000/d/PJfhrbz7z/node-exporter-full-2?orgId=1&refresh=15s&from=now-5m&to=now
wait
#osascript -e "tell app \"Finder\" to display dialog \"$P\"" 
