#!/bin/sh
P=$(cd "$(dirname "$0")"; pwd)
cd $P
../Resources/splash-screen/splash-screen --launch "../Resources/grafana-server/bin/grafana-server" \
	--launch "../Resources/prometheus/prometheus --web.listen-address=127.0.0.1:9090" \
	--launch "../Resources/process-exporter/process-exporter" \
	--launch "../Resources/node_exporter/node_exporter" \
	--launchShell "open http://localhost:3000/d/PJfhrbz7z/node-exporter-full-2?orgId=1&refresh=15s&from=now-5m&to=now"
#osascript -e "tell app \"Finder\" to display dialog \"$P\"" 
