# my global config
global:
  scrape_interval:     5s
  evaluation_interval: 5s
  scrape_timeout:      4s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
