name: grafana-batteries-included
base: core18 # the base snap is the execution environment for this snap
version: "1.0.0" # just for humans, typically '1.2+git' or '1.3.2'
summary: Preconfigured grafana with prometheus and loki # 79 char long summary
description: |
  Preconfigured grafana with prometheus and loki # 79 char long summary
grade: stable
confinement: strict

parts:
  batteries:
    source: batteries
    source-type: local
    plugin: dump
  grafana:
    source: grafana
    source-type: local
    plugin: dump
    build-packages:
      - wget
    override-build: ./build.sh && snapcraftctl build
    stage:
      - -*.linux-amd64.tar.gz*
      - -conf
      - -build.sh
  prometheus:
    source: prometheus
    source-type: local
    plugin: dump
    override-build: ./build.sh && snapcraftctl build
    stage:
      - -*linux-amd64.tar.gz*
      - -build.sh
  exporter:
    source: exporter
    source-type: local
    plugin: dump
    override-build: ./build.sh && snapcraftctl build
    stage:
      - -*linux-amd64.tar.gz*
      - -build.sh

apps:
  grafana-batteries-included:
    command: /bin/sh $SNAP/run/run.sh
